const {
  Document, Packer, Paragraph, TextRun, HeadingLevel,
  InsertedTextRun, DeletedTextRun, AlignmentType
} = require("docx");
const fs = require("fs");

const AUTHOR = "Claude (R6-excluded re-analysis)";
const DATE = "2026-07-27T00:00:00Z";
let idc = 1;
const T = (t, o = {}) => new TextRun({ text: t, ...o });
// deletion then insertion pair (old struck-through, new inserted)
const CH = (oldT, newT) => ([
  new DeletedTextRun({ text: oldT, id: idc++, author: AUTHOR, date: DATE }),
  new InsertedTextRun({ text: newT, id: idc++, author: AUTHOR, date: DATE }),
]);
const INS = (t) => new InsertedTextRun({ text: t, id: idc++, author: AUTHOR, date: DATE });

const para = (children, opts = {}) => new Paragraph({
  children, spacing: { after: 200, line: 300 }, ...opts
});

const doc = new Document({
  creator: AUTHOR,
  title: "Seismic drumming exhibits individual-specific structure (R6-excluded re-analysis)",
  sections: [{
    properties: { page: { size: { width: 12240, height: 15840 } } },
    children: [
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        spacing: { after: 240 },
        children: [ T("Seismic drumming exhibits individual-specific structure") ],
      }),

      // Inserted descriptive-stats note (drums per bout & inter-drum interval)
      para([
        INS("[Descriptive statistics computed on request — these correspond to the earlier "),
        INS("“Robust seismic activity” statement that bursts contained ~5 drum-signals with ~100 ms "),
        INS("intervals. Across the five individuals (R1–R5), drumming bouts contained on average "),
        INS("3.72 ± 0.20 head-drums per bout (mean ± SD across animals; typical within-animal SD ≈ 0.8 drums), "),
        INS("with a mean inter-drum interval of 101.6 ± 5.9 ms (mean ± SD across animals).]"),
      ]),

      // Waveform paragraph
      para([
        T("Our results above suggest that BMRs can identify at least the sex of intruders based on seismic communication. We thus asked whether head-drumming carries individual-specific information, that is, can we identify the signaler based on the drumming. A Random Forest classifier trained on the waveform of the drumming signals achieved "),
        ...CH("90%", "87.8%"),
        T(" balanced accuracy in identifying individuals on a test set (with a macro-F1 "),
        ...CH("0.86", "0.876"),
        T("). Individual-specific identification performance varied, with precision and recall ranging "),
        ...CH("between 0.84 and 0.94", "between 0.80 and 0.95"),
        T(" across individuals (Fig. 4). Permutation tests (100 shuffles) yielded a null mean accuracy of "),
        ...CH("16.46% ± 0.2", "20.0% ± 0.2"),
        T(", indicating performance far above chance (p < 0.01). A Shapley feature importance analysis that examines which features are more important for classification suggested that the classifier relied on individual-specific waveform characteristics, that is, the drumming signals generated by different individuals are individual-specific – no parts of the signal seemed to provide more information than others, suggesting that the classifier used the entire signal’s temporal shape (Fig. 4A)."),
      ]),

      // Noise control paragraph
      para([
        T("To evaluate whether classification could be driven by day-specific recording noise rather than signal structure, we performed a control analysis using noise-only segments. Classification on noise-only segments still produced a moderate accuracy of "),
        ...CH("61.2%", "72.4%"),
        T(" (macro-F1 ≈ 0.67), which was above chance level, but significantly lower than the signal-based individual classification (P<0.00001, based on a Monte-Carlo test). This implies that part of the ability to identify individuals might have resulted from changes in background (e.g., soil) but that there is still much individual information in the drumming signals themselves."),
      ]),

      // Sequence paragraph
      para([
        T("Next, to test whether the temporal structure in the drumming sequence also contained identity cues (in addition to the information contained in single drum-pulses) we trained a Random-Forest model using four sequence parameters: the average inter-drum interval, the inter-drum interval standard deviation, the number of head-drums in the sequence and standard deviation of head-drum amplitudes. These sequence parameters alone enabled significant individual identification, with a balanced accuracy of "),
        ...CH("69.9%", "72.6%"),
        T(", significantly above chance ("),
        ...CH("16.6% ± 4.0", "20.2% ± 4.7"),
        T(", p < 0.01, permutation test). To determine the relative contribution of each parameter to individual identification, we performed a SHAP analysis (mean |SHAP| ± SD across 8 seeds). "),
        // Reordered + renumbered sentence: SD amplitude is now least; mean interval moves to 3rd
        new DeletedTextRun({ id: idc++, author: AUTHOR, date: DATE,
          text: "The number of head-drums in the sequence contributed most strongly to classification (0.0835 ± 0.0047, mean rank 1.38), followed by the SD of inter-drum interval (0.0734 ± 0.0038, mean rank 2.38) and the SD of head-drum amplitude (0.0725 ± 0.0038, mean rank 2.25), while the mean inter-drum interval contributed least (0.0571 ± 0.0028, mean rank 4.00)." }),
        new InsertedTextRun({ id: idc++, author: AUTHOR, date: DATE,
          text: "The number of head-drums in the sequence contributed most strongly to classification (0.0862 ± 0.0056, mean rank 1.12), followed by the SD of inter-drum interval (0.0769 ± 0.0047, mean rank 1.88) and the mean inter-drum interval (0.0652 ± 0.0047, mean rank 3.00), while the SD of head-drum amplitude contributed least (0.0406 ± 0.0041, mean rank 4.00)." }),
        T(" Notably, unlike the signal’s waveform that might change in space making it difficult for individuals to learn, these temporal sequence features are invariant across space and thus should be easier to learn."),
      ]),

      // Cross-session paragraph (UNCHANGED per instruction)
      para([
        T("We further tested whether individual classification could generalize across recording sessions, which would suggest that the same individual can be identified across environments and time. Using waveform features, performance was significantly higher than chance but lower than within-session classification. The mean cross-session accuracy was 43.8% (with a mean macro-F1 of 0.41) relative to chance level accuracy of 24.8% ±0.1 (p < 0.01, permutation test, see Table 3). When running the cross-session individual classification test with sequence parameters only (average number of drums, the inter-drum intervals and their standard deviations), the decrease in classification was less pronounced. Mean cross-session accuracy was 39.9% (relative to chance classification accuracy of 24.9% ± 0.1, p < 0.01, permutation test)."),
      ]),

      // Sex paragraph (conclusion unchanged; re-verified non-significant)
      para([
        T("All attempts to classify sex (independently of individual identity) based on the drumming characteristics yielded non-significant results."),
      ]),

      // Footnote-style note
      new Paragraph({
        spacing: { before: 300 },
        children: [ INS("Note: Round 6 (R6) was excluded from all analyses above (now five individuals, R1–R5), consistent with Fig. 4. The two cross-session (inter-session) sentences were left unchanged per instruction, as they already used only the animals with two sessions (R2–R5) and do not involve R6.") ],
      }),
    ],
  }],
});

Packer.toBuffer(doc).then(b => {
  fs.writeFileSync("Seismic_drumming_individual_structure_R6excluded_tracked.docx", b);
  console.log("wrote docx", b.length, "bytes");
});
